### ISSUE TITLE
confusion bug?

### ISSUE THREAD

**Issue by tigermeet28** [PRHLT/pageDistanceBasedContourGenerator#6]
Hello,
I discovered a problem: Sometimes, when there is a short line in between two long lines, the pDBCG mixes up the Line Texts and IDs.
For example:
https://github.com/PRHLT/pageContourGenerator/blob/master/JA.Jv3-068.jpg
https://github.com/PRHLT/pageContourGenerator/blob/master/JA.Jv3-068.xml.orig

When I run the pDBCG on this document (with no options other than input and output specification) I get the following confusions:

- line 3 gets Text and ID from line 4 and vice versa
- line 11 gets Text and ID from line 12 and vice versa

In EXTRACT mode these confusions are reported:
`1865 [0x7fc0e8955ac0] ERROR PRHLT.Page_File null -  Out of place line >> 2 for 3`
`1901 [0x7fc0e8955ac0] ERROR PRHLT.Page_File null -  Out of place line >> 3 for 2`
`2078 [0x7fc0e8955ac0] ERROR PRHLT.Page_File null -  Out of place line >> 10 for 11`
`2111 [0x7fc0e8955ac0] ERROR PRHLT.Page_File null -  Out of place line >> 11 for 10`

But they're not corrected. So we end up with a wrong ground truth.
The issue occured with other documents as well.

I tried to figure out where the confusion happens. It should be in
`Page_File::load_baselines()` or `Page_File::get_sorted_baselines()`.

**Comment by vbosch** [comment]
Dear tigetmeet, 

I am a bit unsure about the issue, I just downloaded the master of this code pDBCG and executed the example you provided with  -v0 -v1 -v2 and the out of place text does not appear here. Those messages were provided in the other tool to warn the users not to actually do the changes. 

Furthermore uppong extracting the images and text with this tool (pageDistanceBasedContourGenerator) and printing the .txt in order I get exactly the same order as exhibited in the xml. Please see attached image with side by side comparisson of xml and output of txt files and numbers in red. 

![image](https://user-images.githubusercontent.com/318911/82369189-ed55c280-9a16-11ea-823f-11c71a0c5f20.png)

Is this an issue of the pageDistanceContourGenerator tool  or of the pageContourGenerator tool (from where you got the images) ? If it is of the other tool please close this issue and reopen in the other tool, if the issue is of this tool please provide screenshot of exact command call and output. 

Best,
Vicent

**Comment by tigermeet28** [comment]
Dear vbosch,
thanks for your quick and kind reply.
The issue is with the pageDistanceBasedContourGenerator, not with the pageContourGenerator. Just the example file is from pageContourGenerator.
command:
`./extract_lines -i test/JA.Jv3-068.jpg -p test/JA.Jv3-068.xml.orig -o test/output/JA.Jv3-068.xml`

Maybe it's clearer when I describe it this way: The IDs and Unicode texts remain in correct order, but the Baselines (and according TextLine Coords) get mixed up:
![test_marked](https://user-images.githubusercontent.com/65606339/82425672-22016280-9a87-11ea-8faf-8a8b1421bcf0.PNG)

And after running EXTRACT mode, the text files do not fit the image files, so I have a wrong ground truth:
`JA.Jv3-068_02_04_t1_t1_l03.txt`
contains the text for
`JA.Jv3-068_02_03_t1_t1_l04.png`
and vice versa.

**Comment by vbosch** [comment]
Dear tigermeet,

I have now understood your issue and was able to replicate it. It is not very common in HTR to have to generate the contours when the text is already know for each textline. This was causing a bug since I have never encountered this situation. 

The distance based contour program was calling a routine to initially generate fixed sized contours just in case there are issues with the more complex routine and no solution is possible so that you always have a backup solution. This was using the calculated order of baselines "to move stuff around "but the text was not being moved with the rest.

I recommend that when you use the command you set default_above, default_below, upper_dist and lower_dist as per the corpus you are using it on. To get the best results and the best back up results possible. 

I have made a new commit to the code fixing this. Please download and test. When you give me the OK I will close this ( I have also tested but I would like to be double sure).  

(At some point in the future I should do a full rewrite of the page_file class it is messy and the technical debt every time I need to add something or fix something is getting huge. )


Best,
Vicent

**Comment by tigermeet28** [comment]
Dear vbosch,
thanks a lot for your help!
My use case is: I have page-xmls containing baselines and text and I want to extract the line snippets with ground truth to create training data for PyLaia.

I've tested your new commit. The xml output looks good now: Baseline and text are not confused anymore. Just the ID changes - which is probably ok.
![test_marked2](https://user-images.githubusercontent.com/65606339/82646182-6b32ed00-9c14-11ea-9f71-1bae50f86cc8.PNG)

But when I visualize the TextLine Coords with Transkribus, they are still confused: The text does not fit the contour:
![tk1](https://user-images.githubusercontent.com/65606339/82646508-00ce7c80-9c15-11ea-9dbd-c3aa1edf56d7.PNG)
![tk2](https://user-images.githubusercontent.com/65606339/82646542-0c21a800-9c15-11ea-90e8-fc712a3d7aa2.PNG)

As a result, in EXTRACT mode I still get the confusion mentioned before, but now **without the error message** `ERROR PRHLT.Page_File null - Out of place line >>...`


**Before your commit:** Baseline and contour matched, but text did not match.
**Now:** Baseline and text match, but contour is not matching.

Can you confirm this behavior?
Thanks for your work and time. I appreciate it.

**Comment by vbosch** [comment]
Dear Tigermeet, 

I believe I have now fixed this fully. See attached screenshot. Sorry for taking so many iterations to fix this. I am right now in the middle of something else and I am using my free time to review this when I can. 

![image](https://user-images.githubusercontent.com/318911/82832882-bff89100-9ebc-11ea-8265-e55626e032d4.png)

Do let me know if it is now ok for you. Otherwise I guess we will have to do another iteration. 

Best,
Vicent

**Comment by tigermeet28** [comment]
Dear Vicent,
as far as I tested, it works perfectly now. Thank you very much!
No need to apologize! I'm very glad for your free and kind support!
God bless you!
